version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn run:app --host 0.0.0.0"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=superS3cretpassw0rd
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database_scripts:/docker-entrypoint-initdb.d/
